chb-mit:
  root_dir: ../../data/chb-mit/
  meta_dir: ../metadata/chb-mit/
  windows_dir: ../../processeddata/chb/
  models_dir: ../../models/chb-mit/
  exp_dir: ../../explanations/chb-mit/
  metrics_dir: ../../metrics/
  epoch_size: 2           # 2 seconds  
  f_samp: 256             # 256 Hz
  gain: 2.559375
  units: 0.000001  # Microvolts
  patience: 15

  seizure_type: null

  bipolar_channels:
    - [FP1, F7]
    - [F7, T7]
    - [T7, P7]
    - [P7, O1]
    - [FP1, F3]
    - [F3, C3]
    - [C3, P3]
    - [P3, O1]
    - [FP2, F4]
    - [F4, C4]
    - [C4, P4]
    - [P4, O2]
    - [FP2, F8]
    - [F8, T8]
    - [T8, P8]
    - [P8, O2]
    - [FZ, CZ]
    - [CZ, PZ]
    - [T7, FT9]
    - [FT9, FT10]
    - [FT10, T8]


siena:
  root_dir: ../../data/siena/
  meta_dir: ../metadata/siena/
  windows_dir: ../../processeddata/siena/
  models_dir: ../../models/siena/
  exp_dir: ../../explanations/siena/
  metrics_dir: ../../metrics/
  epoch_size: 2           # 2 seconds  
  f_samp: 512
  gain: 1
  units: 0.000001  # Microvolts  
  patience: 15

  seizure_type:
    PN00: IAS-T
    PN01: IAS-T
    PN03: IAS-T
    PN05: IAS-T
    PN06: IAS-T
    PN07: IAS-T
    PN09: IAS-T
    PN10: FBTC-F
    PN11: IAS-T
    PN12: IAS-T
    PN13: IAS-T
    PN14: WIAS-T
    PN16: IAS-T
    PN17: IAS-T

  bipolar_channels:
    - [Fp1, F7]
    - [Fp2, F8]
    - [F7, T3]
    - [F8, T4]
    - [T3, T5]
    - [T4, T6]
    - [T5, O1]
    - [T6, O2]
    - [Fp1, F3]
    - [Fp2, F4]
    - [F3, C3]
    - [F4, C4]
    - [C3, P3]
    - [C4, P4]
    - [P3, O1]
    - [P4, O2]


tusz:
  root_dir: ../../../../Thesis/DataRaw/edf/
  meta_dir: ../../../../Thesis/DataRaw/edf/
  windows_dir: ../../processeddata/tusz/
  models_dir: ../../models/tusz/
  exp_dir: ../../explanations/tusz/
  metrics_dir: ../../metrics/
  epoch_size: 2           # 2 seconds  
  f_samp: 512
  gain: 1
  units: 0.000001  # Microvolts  
  patience: 10

  bipolar_channels:
    - [Fp1, F7]
    - [Fp2, F8]
    - [F7, T3]
    - [F8, T4]
    - [T3, T5]
    - [T4, T6]
    - [T5, O1]
    - [T6, O2]
    - [Fp1, F3]
    - [Fp2, F4]
    - [F3, C3]
    - [F4, C4]
    - [C3, P3]
    - [C4, P4]
    - [P3, O1]
    - [P4, O2]

wang_1d:
  stats: ../../mldata/wang_1d
  images: ../../images/wang_1d
  models: ../../models/wang_1d
  epochs: 100
  max_instances: 8000

wang_2d:
  stats: ../../mldata/wang_2d
  images: ../../images/wang_2d
  models: ../../models/wang_2d
  epochs: 100
  max_instances: 8000

classes:
  0: Normal
  1: Ictal
